# **Exploring Business Use Cases with SQLite in Python**

###In today's lesson we will be exploring the popular business use case for the **Country Club Database**.


---

**Note:** Ensure the `country_club.db` file is in your working directory before running the notebook. Do so by running the line of code below and finding the database created now in your Colab environment within Files.

# **STEP ONE**

*   Import all necessary libraries and packages.
*   Establish the path to the DB stored in Files.

In [2]:
import sqlite3
import pandas as pd

# Set the path to the SQLite database
db_path = "country_club.db"

# Connect to SQLite database
conn = sqlite3.connect(db_path)

# Confirmation
print("Connected to SQLite  database!")

Connected to SQLite  database!

# **The Bookings Table**

In [3]:
query_bookings = """SELECT *
                    FROM bookings;"""

# Execute the query using pd.read_sql.
df_bookings = pd.read_sql(query_bookings, conn)

print(df_bookings)

      bookid  facid  memid            starttime  slots
0          0      3      1  2012-07-03 11:00:00      2
1          1      4      1  2012-07-03 08:00:00      2
2          2      6      0  2012-07-03 18:00:00      2
3          3      7      1  2012-07-03 19:00:00      2
4          4      8      1  2012-07-03 10:00:00      1
...      ...    ...    ...                  ...    ...
4039    4039      8     29  2012-09-30 18:00:00      1
4040    4040      8     21  2012-09-30 18:30:00      1
4041    4041      8     16  2012-09-30 19:00:00      1
4042    4042      8     29  2012-09-30 19:30:00      1
4043    4043      8      5  2013-01-01 15:30:00      1

[4044 rows x 5 columns]

# **The Members Table**

In [4]:
query_members = """SELECT *
                    FROM members;"""

# Execute the query using pd.read_sql
df_members = pd.read_sql(query_members, conn)

print(df_members)

    memid            surname  firstname  \
0       0              GUEST      GUEST
1       1              Smith     Darren
2       2              Smith      Tracy
3       3             Rownam        Tim
4       4           Joplette     Janice
5       5            Butters     Gerald
6       6              Tracy     Burton
7       7               Dare      Nancy
8       8             Boothe        Tim
9       9           Stibbons     Ponder
10     10               Owen    Charles
11     11              Jones      David
12     12              Baker       Anne
13     13            Farrell     Jemima
14     14              Smith       Jack
15     15              Bader   Florence
16     16              Baker    Timothy
17     17             Pinker      David
18     20            Genting    Matthew
19     21          Mackenzie       Anna
20     22             Coplin       Joan
21     24             Sarwin  Ramnaresh
22     26              Jones    Douglas
23     27             Rumney  Henrietta
24     28            Farrell      David
25     29  Worthington-Smyth      Henry
26     30            Purview  Millicent
27     33         Tupperware   Hyacinth
28     35               Hunt       John
29     36            Crumpet      Erica
30     37              Smith     Darren

                                    address  zipcode       telephone  \
0                                     GUEST        0  (000) 000-0000
1                8 Bloomsbury Close, Boston     4321    555-555-5555
2              8 Bloomsbury Close, New York     4321    555-555-5555
3                    23 Highway Way, Boston    23423  (844) 693-0723
4                20 Crossing Road, New York      234  (833) 942-4710
5            1065 Huntingdon Avenue, Boston    56754  (844) 078-4130
6                   3 Tunisia Drive, Boston    45678  (822) 354-9973
7               6 Hunting Lodge Way, Boston    10383  (833) 776-4001
8        3 Bloomsbury Close, Reading, 00234      234  (811) 433-2547
9                 5 Dragons Way, Winchester    87630  (833) 160-3900
10     52 Cheshire Grove, Winchester, 28563    28563  (855) 542-5251
11                 976 Gnats Close, Reading    33862  (844) 536-8036
12                55 Powdery Street, Boston    80743    844-076-5141
13          103 Firth Avenue, North Reading    57392  (855) 016-0163
14               252 Binkington Way, Boston    69302  (822) 163-3254
15               264 Ursula Drive, Westford    84923  (833) 499-3527
16                329 James Street, Reading    58393    833-941-0824
17                   5 Impreza Road, Boston    65332    811 409-6734
18    4 Nunnington Place, Wingfield, Boston    52365  (811) 972-1377
19              64 Perkington Lane, Reading    64577  (822) 661-2898
20      85 Bard Street, Bloomington, Boston    43533  (822) 499-2232
21               12 Bullington Lane, Boston    65464  (822) 413-1470
22                 976 Gnats Close, Reading    11986    844 536-8036
23               3 Burkington Plaza, Boston    78533  (822) 989-8876
24          437 Granite Farm Road, Westford    43532  (855) 755-9876
25              55 Jagbi Way, North Reading    97676  (855) 894-3758
26   641 Drudgery Close, Burnington, Boston    34232  (855) 941-9786
27  33 Cheerful Plaza, Drake Road, Westford    68666  (822) 665-5327
28                5 Bullington Lane, Boston    54333  (899) 720-6978
29              Crimson Road, North Reading    75655  (811) 732-4816
30           3 Funktown, Denzington, Boston    66796  (822) 577-3541

    recommendedby             joindate
0               0  2012-07-01 00:00:00
1               0  2012-07-02 12:02:05
2               0  2012-07-02 12:08:23
3               0  2012-07-03 09:32:15
4               1  2012-07-03 10:25:05
5               1  2012-07-09 10:44:09
6               0  2012-07-15 08:52:55
7               4  2012-07-25 08:59:12
8               3  2012-07-25 16:02:35
9               6  2012-07-25 17:09:05
10              1  2012-08-03 19:42:37
11              4  2012-08-06 16:32:55
12              9  2012-08-10 14:23:22
13              0  2012-08-10 14:28:01
14              1  2012-08-10 16:22:05
15              9  2012-08-10 17:52:03
16             13  2012-08-15 10:34:25
17             13  2012-08-16 11:32:47
18              5  2012-08-19 14:55:55
19              1  2012-08-26 09:32:05
20             16  2012-08-29 08:32:41
21             15  2012-09-01 08:44:42
22             11  2012-09-02 18:43:05
23             20  2012-09-05 08:42:35
24              0  2012-09-15 08:22:05
25              2  2012-09-17 12:27:15
26              2  2012-09-18 19:04:01
27              0  2012-09-18 19:32:05
28             30  2012-09-19 11:32:45
29              2  2012-09-22 08:36:38
30              0  2012-09-26 18:08:45

# **The Facilities Table**

In [5]:
query_facilities = """SELECT *
                    FROM facilities;"""

# Execute the query using pd.read_sql
df_facilities = pd.read_sql(query_facilities, conn)

print(df_facilities)

   facid             name  membercost  guestcost  initialoutlay  \
0      0   Tennis Court 1         5.0       25.0          10000
1      1   Tennis Court 2         5.0       25.0           8000
2      2  Badminton Court         0.0       15.5           4000
3      3     Table Tennis         0.0        5.0            320
4      4   Massage Room 1        35.0       80.0           4000
5      5   Massage Room 2        35.0       80.0           4000
6      6     Squash Court         3.5       17.5           5000
7      7    Snooker Table         0.0        5.0            450
8      8       Pool Table         0.0        5.0            400

   monthlymaintenance
0                 200
1                 200
2                  50
3                  10
4                3000
5                3000
6                  80
7                  15
8                  15



---


# **Exploring the Dataset with Directed Questions**

In [6]:
#Q1: You'd like to get the first and last name of the last member(s) who signed up. Try not to use the LIMIT clause for your solution.
query_last_member = """
SELECT m.firstname, m.surname, m.joindate
FROM members AS m
WHERE m.joindate = (SELECT MAX(joindate) FROM members);
                    """

# Execute the query using pd.read_sql.
df_last_member = pd.read_sql(query_last_member, conn)

print("Question 1")
print(df_last_member)

Question 1
  firstname surname             joindate
0    Darren   Smith  2012-09-26 18:08:45

In [7]:
#Q2: Produce a list of all members who have used a tennis court.
#Include in your output the name of the court, and the name of the member formatted as a single column. Ensure no duplicate data, and order by the member name.
query_tennis_courts = """
SELECT DISTINCT m.firstname ||' '|| m.surname AS mem_name, f.name AS court_name
FROM members AS m
JOIN facilities as f ON f.facid = b.facid
JOIN bookings as b ON b.memid = m.memid
WHERE f.name LIKE 'Tennis%'
ORDER BY mem_name;
                      """
# Execute the query using pd.read_sql.
df_tennis_courts = pd.read_sql(query_tennis_courts, conn)

print("Question 2")
print(df_tennis_courts)

Question 2
             mem_name      court_name
0          Anne Baker  Tennis Court 1
1          Anne Baker  Tennis Court 2
2        Burton Tracy  Tennis Court 2
3        Burton Tracy  Tennis Court 1
4        Charles Owen  Tennis Court 1
5        Charles Owen  Tennis Court 2
6        Darren Smith  Tennis Court 2
7       David Farrell  Tennis Court 1
8       David Farrell  Tennis Court 2
9         David Jones  Tennis Court 2
10        David Jones  Tennis Court 1
11       David Pinker  Tennis Court 1
12      Douglas Jones  Tennis Court 1
13      Erica Crumpet  Tennis Court 1
14     Florence Bader  Tennis Court 2
15     Florence Bader  Tennis Court 1
16        GUEST GUEST  Tennis Court 2
17        GUEST GUEST  Tennis Court 1
18     Gerald Butters  Tennis Court 1
19     Gerald Butters  Tennis Court 2
20   Henrietta Rumney  Tennis Court 2
21         Jack Smith  Tennis Court 1
22         Jack Smith  Tennis Court 2
23    Janice Joplette  Tennis Court 1
24    Janice Joplette  Tennis Court 2
25     Jemima Farrell  Tennis Court 2
26     Jemima Farrell  Tennis Court 1
27        Joan Coplin  Tennis Court 1
28          John Hunt  Tennis Court 1
29          John Hunt  Tennis Court 2
30    Matthew Genting  Tennis Court 1
31  Millicent Purview  Tennis Court 2
32         Nancy Dare  Tennis Court 2
33         Nancy Dare  Tennis Court 1
34    Ponder Stibbons  Tennis Court 2
35    Ponder Stibbons  Tennis Court 1
36   Ramnaresh Sarwin  Tennis Court 2
37   Ramnaresh Sarwin  Tennis Court 1
38         Tim Boothe  Tennis Court 2
39         Tim Boothe  Tennis Court 1
40         Tim Rownam  Tennis Court 2
41         Tim Rownam  Tennis Court 1
42      Timothy Baker  Tennis Court 2
43      Timothy Baker  Tennis Court 1
44        Tracy Smith  Tennis Court 1
45        Tracy Smith  Tennis Court 2

In [8]:
#Q3: Produce a report of members and who recommended them in alphabetic surname,firstname order
query_recommended_by = """
SELECT DISTINCT m1.firstname ||' '|| m1.surname AS mem_name, m2.firstname ||' '|| m2.surname AS rec_name
FROM members AS m1
JOIN members AS m2 ON m2.memid = m1.recommendedby
ORDER BY m1.surname, m1.firstname;
                       """

# Execute the query using pd.read_sql.
df_recommended_by = pd.read_sql(query_recommended_by, conn)

print("Question 3")
display(df_recommended_by)

Question 3

                   mem_name           rec_name
0            Florence Bader    Ponder Stibbons
1                Anne Baker    Ponder Stibbons
2             Timothy Baker     Jemima Farrell
3                Tim Boothe         Tim Rownam
4            Gerald Butters       Darren Smith
5               Joan Coplin      Timothy Baker
6             Erica Crumpet        Tracy Smith
7                Nancy Dare    Janice Joplette
8             David Farrell        GUEST GUEST
9            Jemima Farrell        GUEST GUEST
10              GUEST GUEST        GUEST GUEST
11          Matthew Genting     Gerald Butters
12                John Hunt  Millicent Purview
13              David Jones    Janice Joplette
14            Douglas Jones        David Jones
15          Janice Joplette       Darren Smith
16           Anna Mackenzie       Darren Smith
17             Charles Owen       Darren Smith
18             David Pinker     Jemima Farrell
19        Millicent Purview        Tracy Smith
20               Tim Rownam        GUEST GUEST
21         Henrietta Rumney    Matthew Genting
22         Ramnaresh Sarwin     Florence Bader
23             Darren Smith        GUEST GUEST
24               Jack Smith       Darren Smith
25              Tracy Smith        GUEST GUEST
26          Ponder Stibbons       Burton Tracy
27             Burton Tracy        GUEST GUEST
28      Hyacinth Tupperware        GUEST GUEST
29  Henry Worthington-Smyth        Tracy Smith

In [9]:
#Q4: Some of the facilities charge a fee to members, but some do not. Please list the names of the facilities that do.
query_member_fee = """
SELECT f.name AS fac_name, f.membercost
FROM facilities AS f
WHERE f.membercost > 0;
                   """

# Execute the query using pd.read_sql.
df_member_fee = pd.read_sql(query_member_fee, conn)

print("Question 4")
display(df_member_fee)

Question 4

         fac_name  membercost
0  Tennis Court 1         5.0
1  Tennis Court 2         5.0
2  Massage Room 1        35.0
3  Massage Room 2        35.0
4    Squash Court         3.5

In [10]:
#Q6: How many facilities do not charge a fee to members?

query_no_member_fee = """
SELECT COUNT(f.membercost) AS no_member_fee_count
FROM facilities AS f
WHERE f.membercost = 0;
"""

# Execute the query using pd.read_sql.
df_no_member_fee = pd.read_sql(query_no_member_fee, conn)

print("Question 6")
display(df_no_member_fee)

Question 6

   no_member_fee_count
0                    4

In [11]:
#Q7: Write an SQL query to show a list of facilities that charge a fee to members,
#where the fee is less than 20% of the facility's monthly maintenance cost.
#Return the facid, facility name, member cost, and monthly maintenance of the
#facilities in question.

query_member_fee_less = """
SELECT f.facid, f.name, f.membercost, f.monthlymaintenance
FROM facilities AS f
WHERE f.membercost BETWEEN 0.01 AND 0.20*f.monthlymaintenance;
                        """
# Execute the query using pd.read_sql.
df_member_fee_less = pd.read_sql(query_member_fee_less, conn)

print("Question 7")
display(df_member_fee_less)

Question 7

   facid            name  membercost  monthlymaintenance
0      0  Tennis Court 1         5.0                 200
1      1  Tennis Court 2         5.0                 200
2      4  Massage Room 1        35.0                3000
3      5  Massage Room 2        35.0                3000
4      6    Squash Court         3.5                  80

In [12]:
#Q8: Write an SQL query to retrieve the details of facilities with ID 1 and 5.
query_facid_1_5 = """
SELECT *
FROM facilities
WHERE facid = 1 OR facid = 5;

                  """
# Execute the query using pd.read_sql.
df_facid_1_5 = pd.read_sql(query_facid_1_5, conn)

print("Question 8")
display(df_facid_1_5)

Question 8

,facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
0,1,Tennis Court 2,5.0,25.0,8000,200
1,5,Massage Room 2,35.0,80.0,4000,3000

In [13]:
#Q9: Produce a list of facilities, with each labelled as 'cheap' or 'expensive', depending on if their monthly maintenance cost is more than $100.
#Return the name and monthly maintenance of the facilities in question.
query_cheap_expensive = """

_IncompleteInputError: incomplete input (1008590735.py, line 3)

In [ ]:
#Q10: Produce a list of facilities with a total revenue less than 1000.
#The output of facility name and total revenue, sorted by revenue.
#Remember that there's a different cost for guests and members!
query_total_revenue = """

In [ ]:
#Q11: Find the facilities with their usage by member, but not guests
query_usage_by = """

In [ ]:
#Q12: Find the facilities usage by month. Exclude guests
query_usage_ = """

# **1. Revenue & Financial KPIs**

**Total Revenue per Facility:**

Summing booking slots multiplied by facility costs (guest vs. member rates) to determine which facilities generate the most income.

In [24]:
df_rev_per = pd.read_sql("""SELECT f.name AS facility_name, SUM(
                         CASE 
                            WHEN b.memid = 0 THEN f.guestcost * b.slots
                            ELSE f.membercost * b.slots
                         END) AS total_revenue
                         FROM facilities as f
                         JOIN bookings as b ON b.facid = f.facid
                         GROUP BY f.name
                         ORDER BY total_revenue DESC;
""", conn)

print("Total Revenue per Facility")
display(df_rev_per)

Total Revenue per Facility

     facility_name  total_revenue
0   Massage Room 1        72540.0
1   Massage Room 2        15810.0
2   Tennis Court 2        14310.0
3   Tennis Court 1        13860.0
4     Squash Court        13468.0
5  Badminton Court         1906.5
6       Pool Table          270.0
7    Snooker Table          240.0
8     Table Tennis          180.0

**Average Revenue per Member (ARPM):**

Calculate the total spending (fees + booking costs) per member to identify high-value users.

In [39]:
df_avg_rev = pd.read_sql("""SELECT m.firstname ||' '|| m.surname AS member_name, SUM (b.slots * f.membercost) AS total_spending
                         FROM members as m
                         JOIN bookings as b ON b.memid = m.memid
                         JOIN facilities as f ON f.facid = b.facid
                         WHERE m.memid > 0
                         GROUP BY member_name
                         ORDER BY total_spending DESC
                         ;
""", conn)

print("Total Spending per Member")
display(df_avg_rev)

Total Spending per Member

                member_name  total_spending
0                Tim Rownam          6480.0
1                Tim Boothe          3644.0
2            Gerald Butters          3343.0
3              Burton Tracy          2953.0
4               David Jones          2651.0
5            Jemima Farrell          2466.0
6                Jack Smith          2427.0
7              Darren Smith          2420.0
8                Nancy Dare          2250.0
9             Timothy Baker          2115.0
10             Charles Owen          1919.0
11          Ponder Stibbons          1909.0
12          Matthew Genting          1905.0
13          Janice Joplette          1490.0
14               Anne Baker          1395.0
15         Ramnaresh Sarwin          1039.0
16              Tracy Smith           957.0
17             David Pinker           486.0
18                John Hunt           337.0
19              Joan Coplin           322.0
20           Florence Bader           289.0
21            Erica Crumpet           155.0
22            Douglas Jones           142.0
23            David Farrell           112.0
24           Anna Mackenzie            84.0
25      Hyacinth Tupperware            77.0
26  Henry Worthington-Smyth            70.0
27         Henrietta Rumney            29.0
28        Millicent Purview            22.0

**Guest Fee Revenue:**
Total income generated specifically from non-member guests, indicating the popularity of the club with outside visitors.

In [ ]:
df_guest_rev = pd.read_sql("""SELECT m.firstname ||' '|| m.surname AS guest_name, SUM (b.slots * f.guestcost) AS total_spending
                         FROM members as m
                         JOIN bookings as b ON b.memid = m.memid
                         JOIN facilities as f ON f.facid = b.facid
                         WHERE m.memid = 0
                         GROUP BY guest_name
                         ;
""", conn)

print("Total Spending for Guests")
display(df_guest_rev)

Total Spending for Guests

    guest_name  total_spending
0  GUEST GUEST         89096.5

**Facility Cost Recovery:**
Comparing the revenue generated by a facility to the frequency of its use to determine if rates need adjustment.

In [3]:
df_fac_cost = pd.read_sql("""SELECT f.name AS facility_name, SUM(b.slots) AS total_uses, SUM(
                         CASE 
                            WHEN b.memid = 0 THEN f.guestcost * b.slots
                            ELSE f.membercost * b.slots
                         END) AS total_revenue
                         FROM bookings as b
                         JOIN facilities as f ON f.facid = b.facid
                         GROUP BY f.name
                         ORDER BY total_uses DESC, total_revenue DESC
                         ;
""", conn)

print("Total Spending for Guests")
display(df_fac_cost)

NameError: name 'pd' is not defined

# **2. Usage & Operational KPIs**

**Facility Utilization Rate (Booking Density):** The ratio of booked hours to total available operating hours for facilities

**Member-to-Guest Ratio:** Tracking how many guests are brought by members to measure member satisfaction (acting as advocates).



---


# **Furthering Our Business Understanding**